# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8365359cb0081a0a3a859eae95d6b095898b802f2561f53f646656629a60de2247c27dbeaf69d6d161594868aece0bfd80c3df7699b6d3cfa6f49da0a7baa534

test:
  secret_key_base: f83346996ae70af9a97a1ff1efb20fb80ce0817e8807605f065caec2d8544c9b09d79ec70a78b2f6fde304ad499fcb54e486dc02f9d5678f5c932dc8fc6d1026

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 47cd9b644f268d2c0c33ce9a2ca5c4c05ce2ab1b379c4617135e258e30cb7e372a7f2845270fc7c13c06edb9b19f0ac846f19140f1d80fd9e5fc3b6526844184
